# For now this just does a clean build and start/stop the server because the test suites
# hang.  https://github.com/dylan-lang/http/issues/90

name: tests

on:
  push:
    # all branches
  pull_request:
    branches:
      - main
      - master

  # This enables the Run Workflow button on the Actions tab.
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v5

      - uses: dylan-lang/install-opendylan@v3

      - name: make install
        env:
          DYLAN: dylan-root
        run: |
          deft update
          make install

      - name: Run http-server --help
        run: |
          dylan-root/bin/http-server --help
